---
title: "variable_genes"
author: "EF"
date: "29 April 2016"
output: html_document
---
# start_section
  
```{r start_section}

# Time stamp
Sys.time()

# Clean up
rm(list=ls())
graphics.off()

# Set root working folder
library(knitr)
library(dplyr)
library(ggplot2)

opts_knit$set(root.dir = "C:/data_local/Control_data/1K_genomes/")
setwd("C:/data_local/Control_data/1K_genomes/")

```

#Load data
```{r load data}
exons_original.df <- read.table("kgen_variableregion_20160504.csv", header=TRUE, row.names=1, sep=",", quote="")
exons.df <- exons_original.df[exons_original.df$length > 6,]
short.df <- exons.df[exons.df$length <2000,]
rm(exons_original.df)
```

#Add columns to data
```{ r add col}
total_exons <- as.data.frame(count(exons_original.df, geneID))
shorted.df <- inner_join(short.df, total_exons, by="geneID")
shorted.df$exon_pos <- (shorted.df$exon/shorted.df$n)*100
colnames(shorted.df)[10] <- "total_exons"

```

#Make scatter of variability versus exon position
```{r variability scatter}
variable.dat <- ggplot(data=shorted.df, (aes(x=exon_pos, y=variable)))
variable.dat + geom_point()
#create mean of variability at each pos
mean_var <- group_by(shorted.df,exon_pos) %>% summarise(mean = mean(variable))
mean_var.dat <- ggplot(data=mean_var, (aes(x=exon_pos, y=mean)))
mean_var.dat + geom_point()

###
mean_var <- group_by(short.df,exon_pos) %>% summarise(mean = mean(VARIABILITY))
mean_var.dat <- ggplot(data=mean_var, (aes(x=exon_pos, y=mean)))
mean_var.dat + geom_point()
```

#Make histograms
```{r hists}
#Histogram of exon lengths
library(Rmisc)
exons.sum <- summarySE(exons.df, measurevar="length", groupvars=c("length"))

ggplot(data=exons.df, aes(x=length)) +
  geom_histogram(stat="bin", position="dodge", colour="black", binwidth=10) +
  scale_fill_brewer(palette="Greys")+
  scale_x_continuous(name= "Exon length", limits=c(0, 500))

#Histogram of number of exons
exonno.sum <- summarySE(exons.df, measurevar="geneID", groupvars=c("geneID"))

ggplot(data=exonno.sum, aes(x=N)) +
  geom_histogram(stat="bin", position="dodge", colour="black", binwidth=2) +
  scale_fill_brewer(palette="Greys")+
  scale_x_continuous(name= "Number of exons", limits=c(0, 100))

```

#Create scatter of exon length vs no of exons
```{r scatter}
total_exons <- as.data.frame(count(short.df, "geneID"))
short.df <- inner_join(short.df, total_exons, by="geneID")
exon.dat <- ggplot(data=short.df,aes(x=exon, y=length, colour=freq, alpha=freq))
exon.dat + geom_point(alpha=0.7) + 
  scale_colour_gradient2(low="yellow", mid="orange", high="red") +
  scale_alpha_continuous(range = c(0.3,1)) +
  scale_x_continuous(name= "Exon number", limits=c(0, 100))

```

#From hists create 'average' data that falls within majority
```{r average}
shorter.df <- shorted.df[shorted.df$freq < 30,]
av.df <- shorter.df[shorter.df$length < 250,]

```
#Calculate position of exon as % of total exons
```{r exon pos}
exon.dat <- ggplot(data=short.df,aes(x=exon_pos, y=length, colour=exon))
exon.dat + geom_point() +
  scale_colour_gradient2(low="yellow", mid="orange", high="red", midpoint = 50) +
  scale_x_continuous(name= "Exon position", limits=c(0, 100))
```

#Create scatter of average data exon length vs no of exons
```{r scatter average}
#create table of mean and iqr exon lengths by exon number
aggr.df <- aggregate(shorter.df[,7], list(shorter.df$exon), mean)
av.aggr.df <- aggregate(av.df[,7], list(av.df$exon), mean)
pos.aggr.df <- aggregate(short.df[,7], list(short.df$exon_pos), mean)

col.names <- pos.aggr.df
```
