---
title: "variable_genes"
author: "EF"
date: "25 May 2016"
output: html_document
---
# start_section
  
```{r start_section}

# Time stamp
Sys.time()

# Clean up
rm(list=ls())
graphics.off()

# Set root working folder
library(knitr)
library(dplyr)
library(ggplot2)
library(stringr)

opts_knit$set(root.dir = "/scratch/medgen/users/eleanor/2015-16/R_scripts/")
setwd("/scratch/medgen/users/eleanor/2015-16/R_scripts/")

```
#Load data
```{r original data}
var <- read.table("variability_annotated_nonsyn_R_20160524.csv", sep= ",", header=TRUE)
dim(var)
```

#Create combined score
```{r combined}
var$VARIABILITY[is.na(var$VARIABILITY)] <- 0
var$VARIABILITY[is.infinite(var$VARIABILITY)] <- 0

comb <- var %>% group_by(geneID) %>% mutate(COMBINED_SCORE = sum(VARIABILITY*count)/total_exons)

comb$COMBINED_SCORE[is.na(comb$COMBINED_SCORE)] <- 0
```

#Set labels for combined_variability
```{r set labels}
#percentage of variants above mean
mean_var <- median(comb$COMBINED_SCORE)
(sum(comb$COMBINED_SCORE > mean_var)/nrow(comb))*100
summary <- as.table(summary(comb$COMBINED_SCORE))
summary

#set values
low <- comb[comb$COMBINED_SCORE <= summary[2],]
low$score <- "low"
midlow <- comb[comb$COMBINED_SCORE > summary[2] & comb$COMBINED_SCORE <= summary[3],]
midlow$score <- "mid_low"
midhigh <- comb[comb$COMBINED_SCORE > summary[3] & comb$COMBINED_SCORE <= summary[5],]
midhigh$score <- "mid_high"
high <-comb[comb$COMBINED_SCORE > summary[5],]
high$score <- "high"

#merge rows and tidy
merge.scores.df <- bind_rows(low, midlow, midhigh, high)
clean.df <- mutate(merge.scores.df, CHROM=str_replace_all(CHR, pattern="chr", ""))

#write csv
write.csv(clean.df, file= "variability_thresholds_combinedscore_nonsyn_20160525.csv", quote=FALSE)
```
